### ISSUE TITLE
Failed to create channel

### ISSUE THREAD

**Issue by Kryptedbbkick** [nopeads/Discord-Server-Cloner#1]
I got everything running right but this seems to be my output.

![Screenshot 2024-03-31 151849](https://github.com/nopeads/Discord-Server-Cloner/assets/22475186/32ebeeb2-89fa-46ef-9efe-8138be9acf16)
![Screenshot 2024-03-31 152731](https://github.com/nopeads/Discord-Server-Cloner/assets/22475186/72d0d7ad-efc7-4c95-89db-fef6517db7d4)

**Comment by nopeads** [comment]
**Stay tuned as the updated version will be shared soon.**
